apiVersion: v1
kind: Service
metadata:
  name: dccn-tendermint
  labels:
    app: dccn-tendermint
spec:
  selector:
    app: dccn-tendermint
  ports:
  - name: tendermint-rpc
    port: 26657
    targetPort: 26657

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      containers:
      - name: tendermint
        image: tendermint/tendermint
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args: ["/usr/bin/tendermint init && /usr/bin/tendermint node --proxy_app=kvstore"]
        ports:
        - containerPort: 26657
          name: tendermint-rpc