# UPGRADE: Go Docker image
FROM golang:alpine

RUN apk update && apk add git && apk add --update bash && apk add openssh
RUN go get github.com/golang/dep/cmd/dep

WORKDIR $GOPATH/src/dccn-daemon
COPY . $GOPATH/src/dccn-daemon

EXPOSE 8080

CMD go run main.go --ip hub.ankr.network --port 50051 --dcName ankr_datacenter1 --kubeconfig ankr.conf
