[[constraint]]
  branch = "feature/swdev-110-ankr_rpc"
  name = "github.com/Ankr-network/dccn-rpc"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[prune]
  go-tests = true
  unused-packages = true
