# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region us-west-2)

      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t hello-go .
            docker tag hello-go:latest 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:hello-go
            docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:hello-go
