# UPGRADE: Deployment API version
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-daemon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-daemon
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: dccn-daemon
        image: "815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-daemon:feat"
        imagePullPolicy: Always
        command: ["sh"] # kubernetes bug: https://github.com/kubernetes/kubernetes/issues/57726
        args: ["-c","dccn-daemon start datacenter_name -s $URL_BRANCH -p 50051 -n test-deploy -S dccn-tendermint -v2"]
