apiVersion: v1
kind: Service
metadata:
  name: dccn-tendermint
  labels:
    app: dccn-tendermint
spec:
  selector:
    app: dccn-tendermint
  ports:
  - name: tendermint-rpc
    port: 26657
    targetPort: 26657

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:feat
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["/usr/bin/tendermint init && /usr/bin/tendermint node --proxy_app=kvstore"]
        ports:
        - containerPort: 26657
          name: tendermint-rpc