apiVersion: v1
kind: Service
metadata:
  name: dccn-tendermint
  labels:
    app: dccn-tendermint
spec:
  selector:
    app: dccn-tendermint
  type: ClusterIP
  ports:
  - name: p2p
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657
  - name: abci
    port: 26658
    targetPort: 26658

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:feat
        imagePullPolicy: Always
        ports:
        - name: p2p
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658
