// Code generated by "stringer -type msgStatus"; DO NOT EDIT.

package daemon

import "strconv"

const _msgStatus_name = "StartFailureStartSuccessCancelFailureCancelledUpdateFailureUpdateSuccess"

var _msgStatus_index = [...]uint8{0, 12, 24, 37, 46, 59, 72}

func (i msgStatus) String() string {
	if i < 0 || i >= msgStatus(len(_msgStatus_index)-1) {
		return "msgStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _msgStatus_name[_msgStatus_index[i]:_msgStatus_index[i+1]]
}
