// Code generated by "stringer -type taskType"; DO NOT EDIT.

package daemon

import "strconv"

const _taskType_name = "NewTaskUpdateTaskCancelTaskListTaskHeartBeat"

var _taskType_index = [...]uint8{0, 7, 17, 27, 35, 44}

func (i taskType) String() string {
	if i < 0 || i >= taskType(len(_taskType_index)-1) {
		return "taskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _taskType_name[_taskType_index[i]:_taskType_index[i+1]]
}
