kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daemon-deployment
  namespace: default
  labels:
    app: dccn-daemon
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-daemon
  apiGroup: rbac.authorization.k8s.io
